### ISSUE TITLE
138a:0097 error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0

### ISSUE THREAD

**Issue by petRUShka** [3v1n0/libfprint#10]
If I try to initialize sensor I get an error: `Unknown flash IC. JEDEC id=ff:ff, size=4096x0`.

Full log:

```
$ sudo validity-sensors-tools -t initializer

Found device <DEVICE ID 138a:0097 on Bus 001 Address 004>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1mgf03w.exe to extract 6_07f_lenovo_mis.xpfwext
Extracting "Synaptics Metallica MOC Touch Fingerprint Reader Driver for Windows 8.1 64-bit" - setup data version 5.5.0
 - "app/WBF_Drivers/6_07f_lenovo_mis.xpfwext"
Done.
Found firmware at /tmp/tmpytble5_s/app/WBF_Drivers/6_07f_lenovo_mis.xpfwext
The device will be now reset to factory and associated to the current laptop.
Press Enter to continue (or Ctrl+C to cancel)...
Opening device 0x97
Factory reset...
Sleeping...
Try 1 failed with error: Failed: 0404
Sleeping...
Try 2 failed with error: Failed: 0404
Sleeping...
Try 3 failed with error: Failed: 0404
Device didn't reply in time...
Factory reset failed with Failed: 0404, this should not happen, but we can ignore it, if pairing works...
Sleeping...
Pairing the sensor with device 20HR000FUS
Opening device 0x97
Initializing flash...
Sleeping...
Try 1 failed with error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
Opening device 0x97
Initializing flash...
Sleeping...
Try 2 failed with error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
Opening device 0x97
Initializing flash...
Sleeping...
Try 3 failed with error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
Opening device 0x97
Initializing flash...
Sleeping...
Try 4 failed with error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
Opening device 0x97
Initializing flash...
Sleeping...
Try 5 failed with error: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
Device didn't reply in time...
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-tools", line 339, in <module>
    vfs_tools.initialize(fwpath, args.calibration_data)
  File "/usr/bin/validity-sensors-tools", line 249, in initialize
    self.pair(fwpath, calib_data)
  File "/usr/bin/validity-sensors-tools", line 220, in pair
    self.retry_command(init_flash_command, max_retries=5)
  File "/usr/bin/validity-sensors-tools", line 112, in retry_command
    raise(err)
  File "/usr/bin/validity-sensors-tools", line 103, in retry_command
    command()
  File "/usr/bin/validity-sensors-tools", line 219, in init_flash_command
    init_flash()
  File "/usr/lib/python3.8/site-packages/proto9x/init_flash.py", line 97, in init_flash
    partition_flash(flash_layout_hardcoded, client_public)
  File "/usr/lib/python3.8/site-packages/proto9x/init_flash.py", line 70, in partition_flash
    info = get_flash_info()
  File "/usr/lib/python3.8/site-packages/proto9x/flash.py", line 38, in get_flash_info
    raise Exception('Unknown flash IC. JEDEC id=%x:%x, size=%dx%d' % (jid0, jid1, blocks, blocksize))
Exception: Unknown flash IC. JEDEC id=ff:ff, size=4096x0
```

P.S. Arch linux, kernel `Linux lparch 5.4.66-1-lts #1 SMP Thu, 17 Sep 2020 18:00:06 +0000 x86_64 GNU/Linux`

Installed packages:
```
local/fprintd-clients 1.90.1.r2.g54e56d6-2
    Fprintd without the daemon
local/libfprint-vfs009x-git 1:1.90.1.r0.g82aed23-2 (fprint-git)
    Library for fingerprint readers (includes libre vfs0090 and vfs0097 driver)
local/open-fprintd 0.5-2
    Fprintd replacement which allows you to have your own backend as a standalone service
local/python-validity 0.9-2
    Validity fingerprint sensor driver
local/validity-sensors-tools-git 0.5.r27.g5ba2094-2
    Linux tool to flash and pair Validity fingerprint sensors 009x
```

**Comment by kotbullar** [comment]
Same here: 
```
`sudo validity-sensors-tools.initializer 
Found device <DEVICE ID 138a:0097 on Bus 001 Address 007>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1mgf03w.exe to extract 6_07f_lenovo_mis.xpfwext
Extracting "Synaptics Metallica MOC Touch Fingerprint Reader Driver for Windows 8.1 64-bit" - setup data version 5.5.0
 - "app/WBF_Drivers/6_07f_lenovo_mis.xpfwext"
Done.
Found firmware at /tmp/tmpufge6ok6/app/WBF_Drivers/6_07f_lenovo_mis.xpfwext
The device will be now reset to factory and associated to the current laptop.
Press Enter to continue (or Ctrl+C to cancel)...
Opening device 0x97
Factory reset...
Sleeping...
Try 1 failed with error: Failed: 0404
Sleeping...
Try 2 failed with error: Failed: 0404
Sleeping...
Try 3 failed with error: Failed: 0404
Device didn't reply in time...
Factory reset failed with Failed: 0404, this should not happen, but we can ignore it, if pairing works...
Sleeping...
Pairing the sensor with device 20JES15D01
Opening device 0x97
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Sleeping...
Try 1 failed with error: Failed: 04af
Opening device 0x97
Initializing flash...
Sleeping...
Try 2 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 3 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 4 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 5 failed with error: Unexpected TLS version 4 0
Device didn't reply in time...
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 339, in <module>
    vfs_tools.initialize(fwpath, args.calibration_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 249, in initialize
    self.pair(fwpath, calib_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 220, in pair
    self.retry_command(init_flash_command, max_retries=5)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 112, in retry_command
    raise(err)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 103, in retry_command
    command()
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 219, in init_flash_command
    init_flash()
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 97, in init_flash
    partition_flash(flash_layout_hardcoded, client_public)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 70, in partition_flash
    info = get_flash_info()
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/flash.py", line 28, in get_flash_info
    rsp=tls.cmd(unhex('3e'))
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 104, in cmd
    rsp=self.app(cmd)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 138, in app
    return self.parse_tls_response(self.usb.cmd(self.make_app_data(b)))
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 336, in parse_tls_response
    raise Exception('Unexpected TLS version %d %d' % (mj, mn))
Exception: Unexpected TLS version 4 0`

```
Kernel:
```
       Operating System: Debian GNU/Linux 10 (buster)
       Kernel: Linux 4.19.0-12-amd64
      Architecture: x86-64
```

**Comment by headbank** [comment]
@kotbullar It looks like your error is different: "Unexpected TLS version 4 0". That's what I am getting too (Thinkpad x270, Gentoo).
