### ISSUE TITLE
not possible to enroll finger

### ISSUE THREAD

**Issue by rootsh0pf** [3v1n0/libfprint#24]
I'm running dualboot Windows and Ubuntu 20.10 on a Lenovo Thinkpad Yoga 370 which has a 138a:0097 fingerprint reader. I installed libfprint-2-tod-vfs0090 from your PPA and validity-sensors-tools from snap. I enrolled my finger in Windows and tried to enroll it also in Ubuntu but it does not work:
`sudo validity-sensors-tools -t enroll
Found device <DEVICE ID 138a:0097 on Bus 001 Address 005>
Opening device 0x97
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 379, in <module>
    vfs_tools.open_device(init=True)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 127, in open_device
    vfs_tls.parseTlsFlash(read_flash(1, 0, 0x1000))
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 414, in parseTlsFlash
    self.handle_priv(body)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 512, in handle_priv
    raise Exception('Point is not on the curve')
Exception: Point is not on the curve`
fprintd-enroll also fails with no devices available

**Comment by rootsh0pf** [comment]
Does someone know, what the exception "Point is not on the curve" means?
