### ISSUE TITLE
Initializer fails: Unexpected TLS Version 4 0

### ISSUE THREAD

**Issue by flofeld** [3v1n0/libfprint#26]
I am running arch and got stuck in the initialization process

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Found device <DEVICE ID 138a:0097 on Bus 001 Address 004>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1mgf03w.exe to extract 6_07f_lenovo_mis.xpfwext
Extracting "Synaptics Metallica MOC Touch Fingerprint Reader Driver for Windows 8.1 64-bit" - setup data version 5.5.0
 - "app/WBF_Drivers/6_07f_lenovo_mis.xpfwext"
Done.
Found firmware at /tmp/tmpg2p72nqj/app/WBF_Drivers/6_07f_lenovo_mis.xpfwext
The device will be now reset to factory and associated to the current laptop.
Press Enter to continue (or Ctrl+C to cancel)...
Opening device 0x97
Factory reset...
Sleeping...
Pairing the sensor with device 20HES01100
Opening device 0x97
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Sleeping...
Try 1 failed with error: Failed: 04af
Opening device 0x97
Initializing flash...
Sleeping...
Try 2 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 3 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 4 failed with error: Unexpected TLS version 4 0
Opening device 0x97
Initializing flash...
Sleeping...
Try 5 failed with error: Unexpected TLS version 4 0
Device didn't reply in time...
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 339, in <module>
    vfs_tools.initialize(fwpath, args.calibration_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 249, in initialize
    self.pair(fwpath, calib_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 220, in pair
    self.retry_command(init_flash_command, max_retries=5)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 112, in retry_command
    raise(err)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 103, in retry_command
    command()
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 219, in init_flash_command
    init_flash()
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 97, in init_flash
    partition_flash(flash_layout_hardcoded, client_public)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 70, in partition_flash
    info = get_flash_info()
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/flash.py", line 28, in get_flash_info
    rsp=tls.cmd(unhex('3e'))
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 104, in cmd
    rsp=self.app(cmd)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 138, in app
    return self.parse_tls_response(self.usb.cmd(self.make_app_data(b)))
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/tls.py", line 336, in parse_tls_response
    raise Exception('Unexpected TLS version %d %d' % (mj, mn))
Exception: Unexpected TLS version 4 0
```

Is there something I can do about it?

**Comment by gaidap** [comment]
Hi, encountered the same problem on Ubuntu 20.04 on my ThinkPad T470s.

**Comment by danielfreyr10** [comment]
Hi, I also encountered the same error on a Thinkpad X1 with Linux Mint 20.1

**Comment by reyhankim** [comment]
Hello, I also encountered this same error in Thinkpad Yoga 370 with Ubuntu 20.04

**Comment by btnpushnmunky** [comment]
Same issue on Thinkpad P50 with Pop!_OS 21.04.

**Comment by synaps13** [comment]
Same on 
Ubuntu 21.04
ThinkPad t470s
138a:0097 Validity Sensors, Inc.

**Comment by steinhmor** [comment]
Same on Pop!_OS 21.04 (based on Ubuntu)
Thinkpad T470
138a:0097 Validity Sensors, Inc.

**Comment by JustinJohnsonBlues** [comment]
Same on Thinkpad X1 5th with Ubuntu 20.04

**Comment by kambiz** [comment]
I too am having this error upon initialization. I have a ThinkPad T470 with Fedora 35. I type lsusb and I have a 138a:0097 device. 

After snapd and the validity package and during the initialization; I get this error. Anyone found a fix to this?

**Comment by stefanokan** [comment]
Same on Thinkpad T570 with Linux Mint 20.2 XFCE:
[error.txt](https://github.com/3v1n0/libfprint/files/7640209/error.txt)

**Comment by squarecode** [comment]
For anyone still searching for a solution and because this project seems to be dead:
**Have a look at this one** https://github.com/uunicorn/python-validity

Working fine for me on my t470s

**Comment by btnpushnmunky** [comment]
> For anyone still searching for a solution and because this project seems to be dead: **Have a look at this one** https://github.com/uunicorn/python-validity
> 
> Working fine for me on my t470s

This did not work for me on my P50.

**Comment by MartinX3** [comment]
@squarecode that won't work.
You compare a hardware driver with a python userland tool to access a hardware driver.

**Comment by plabadens** [comment]
@MartinX3 That is incorrect, the python-validity driver accesses the device directly (likely through libusb bindings). I was able to test this out in a Python REPL on my x270. Also, fprintd is a userland tool as well, as it does not run in the kernel.
The difference between this project and [uunicorn/python-validity](https://github.com/uunicorn/python-validity) is that this one is an fprintd fork that handles the device directly, whereas the other is a (different) fprintd fork that uses dbus to communicate with a userland driver written in python.

**Comment by MartinX3** [comment]
@plabadens that is incorrect
https://github.com/uunicorn/python-validity is no fprintd fork.
100% of its code is written in python. You still need a fprintd driver package on your computer.
And you repeat me and combine it with a wrong explaination.

**Comment by plabadens** [comment]
It requires `open-fprintd`, a fork of `fprintd` by the author of `python-validity` to work: https://github.com/uunicorn/open-fprintd

**Comment by MartinX3** [comment]
Yes, it requires an fprintd package and is not a frpintd fork itself, like I already said 2 times...

**Comment by ChrissyAFK** [comment]
Hi, Same issue on Thinkpad x1 carbon 6th gen running endeavourOS (arch distro) 
06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader

**Comment by raz0229** [comment]
Still fails to enroll for my Lenovo P50 138a:0090

**Comment by abear1538** [comment]
You all can stop commenting that it's still not working.

This project was abandoned a long time ago.

**Comment by MartinX3** [comment]
The last comment was 3 months ago.  

And I use my comment to greet my mother.
Hi mom!

**Comment by MartinX3** [comment]
> You all can stop commenting that it's still not working.
> 
> This project was abandoned a long time ago.

The last comment was 3 months ago.  

And I use my comment to greet my mother.
Hi mom!

**Comment by hualayn** [comment]
same. x1 carbon, debian 13, still no solution, so depressed

**Comment by rabbitambulance-ra** [comment]
i had my clanker sort this out for me earlier today on my X1 Yoga Gen 1 with a Synaptics Metallica 138a:0090: https://github.com/rabbitambulance-ra/libfprint/tree/vfs0090

maybe this will help others. if it helps you, please thumbs up, heart, rocket, or whatever feelings you are feeling. if it doesn't, go ahead and thumbs down, or frown, or whatever helps make you feel better...
