### ISSUE TITLE
Fails to enroll fingerptint

### ISSUE THREAD

**Issue by vonschutter** [3v1n0/libfprint#31]
Device:
Bus 001 Device 010: ID 138a:0090 Validity Sensors, Inc. VFS7500 Touch Fingerprint Sensor

Initialize: 
Appears to work ... 

sudo validity-sensors-tools.initializer 
Found device <DEVICE ID 138a:0090 on Bus 001 Address 010>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1cgn08w.exe to extract 6_07f_Lenovo.xpfwext
Extracting "Synaptics Metallica MOH Touch Fingerprint Reader Driver" - setup data version 5.5.7
 - "app/WBF_Drivers/6_07f_Lenovo.xpfwext"
Done.
Found firmware at /tmp/tmp_8xibwvx/app/WBF_Drivers/6_07f_Lenovo.xpfwext
The device will be now reset to factory and associated to the current laptop.
Press Enter to continue (or Ctrl+C to cancel)...
Opening device 0x90
Factory reset...
Sleeping...
Pairing the sensor with device 20FCS1C300
Opening device 0x90
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Sleeping...
Opening device 0x90
Clean slate
Uploading firmware...
Sensor: VSI 55E  FM72-002  
Loaded FWExt version 1.0 (Tue Nov  8 10:05:20 2016), 6 modules
Sleeping...
Opening device 0x90
Calibrating using device data
Sensor: VSI 55E  FM72-002  
FWExt version 1.0 (Tue Nov  8 10:05:20 2016), 6 modules
len=131480
Calibration data saved at /tmp/tmp9dutil8_/calib-data.bin
Init database...
Creating a new user storage object
Creating a host machine GUID record
That's it, pairing with <DEVICE ID 138a:0090 on Bus 001 Address 010> finished
May the leds be with you...!

Enrolling fingerprint: 
sudo validity-sensors-tools.enroll --finger-id 0
Found device <DEVICE ID 138a:0090 on Bus 001 Address 012>
Opening device 0x90
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 380, in <module>
    vfs_tools.enroll(finger=args.finger_id)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 270, in enroll
    raise Exception('Enroll not supported yet for device {}'.format(
Exception: Enroll not supported yet for device 0x90
 
Soooooo what is upposed to happen here...?  I am expecting it to propt for me to enroll a finger... is that not what is supposed to happen?

**Comment by Pshemas** [comment]
I have the same issue. I can blink the sensor (0090 one) and I can run :

validity-sensors-tools -t initializer

- and I get the message about downloading firmware and so on.
But I don't know what to do next. Readme talks about launching Windows in VM and doing something, but I don't know what exactly - this is my first device with such sensor (and sadly for my first experience I got the one that has issues on Linux :/ ).
BTW - thank you for trying to support this one in an unofficial way.

**Comment by ToniCipriani** [comment]
On my Yoga 260 with the same sensor, I can enroll 1 finger, but it always fails to validate. When I try to enroll a second finger, fprintd always throws an error.
