### ISSUE TITLE
Failed to restore initial working directory

### ISSUE THREAD

**Issue by zeeshanali1993** [3v1n0/libfprint#37]
Unable to execute this on my Thinkpad T460s
```
sudo validity-sensors-tools.initializer                                                                                     ✔ 
[sudo] password for user: 
Found device <DEVICE ID 138a:0090 on Bus 001 Address 004>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1cgn08w.exe to extract 6_07f_Lenovo.xpfwext
Extracting "Synaptics Metallica MOH Touch Fingerprint Reader Driver" - setup data version 5.5.7
 - "app/WBF_Drivers/6_07f_Lenovo.xpfwext"
Done.
find: Failed to restore initial working directory: /home/user: Permission denied
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 329, in <module>
    fwpath = vfs_tools.download_and_extract_fw(fwdir,
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 163, in download_and_extract_fw
    fwpath = subprocess.check_output([
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['find', '/tmp/tmpxujopoha', '-name', '6_07f_Lenovo.xpfwext']' returned non-zero exit status 1.
```

**Comment by jprikner** [comment]
You need to change your current working directory to `/tmp` before you execute the initializer command, then it should work. Apparently, despite running the command with sudo, `find` executes itself as some other user and expects to be run inside the `/tmp` directory, otherwise will fail due to the permission issue.

**Comment by JPapir** [comment]
Thanks, I had the same problem, and this indeed helped.
