### ISSUE TITLE
validity-sensors-tools.initalizer failed with error: Flash is already partitioned

### ISSUE THREAD

**Issue by godlessamerica** [3v1n0/libfprint#41]
Can't get `sudo validity-sensors-tools.initializer` to run 
Thinkpad X1 Carbon Gen 5

```
Found device <DEVICE ID 138a:0097 on Bus 001 Address 004>
Downloading https://download.lenovo.com/pccbbs/mobiles/n1mgf03w.exe to extract 6_07f_lenovo_mis.xpfwext
Extracting "Synaptics Metallica MOC Touch Fingerprint Reader Driver for Windows 8.1 64-bit" - setup data version 5.5.0
 - "app/WBF_Drivers/6_07f_lenovo_mis.xpfwext"
Done.
Found firmware at /tmp/tmp5wy1sqzw/app/WBF_Drivers/6_07f_lenovo_mis.xpfwext
The device will be now reset to factory and associated to the current laptop.
Press Enter to continue (or Ctrl+C to cancel)...
Opening device 0x97
Factory reset...
Sleeping...
Pairing the sensor with device 20HR0057US
Opening device 0x97
Sleeping...
Try 1 failed with error: 'NoneType' object has no attribute 'default_timeout'
Opening device 0x97
Initializing flash...
Sleeping...
Try 2 failed with error: [Errno 16] Resource busy
Opening device 0x97
Initializing flash...
Sleeping...
Try 3 failed with error: [Errno 16] Resource busy
Opening device 0x97
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Sleeping...
Try 4 failed with error: Flash is already partitioned
Opening device 0x97
Initializing flash...
Detected Flash IC: W25Q80B, 1048576 bytes
Sleeping...
Try 5 failed with error: Flash is already partitioned
Device didn't reply in time...
Traceback (most recent call last):
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 339, in <module>
    vfs_tools.initialize(fwpath, args.calibration_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 249, in initialize
    self.pair(fwpath, calib_data)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 220, in pair
    self.retry_command(init_flash_command, max_retries=5)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 112, in retry_command
    raise(err)
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 103, in retry_command
    command()
  File "/snap/validity-sensors-tools/65/vfs-tools/validity-sensors-tools.py", line 219, in init_flash_command
    init_flash()
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 97, in init_flash
    partition_flash(flash_layout_hardcoded, client_public)
  File "/snap/validity-sensors-tools/65/vfs-tools/proto9x/init_flash.py", line 75, in partition_flash
    raise Exception('Flash is already partitioned')
Exception: Flash is already partitioned

**Comment by Dreta** [comment]
I also faced this problem, and I was only able to solve it by creating a Windows virtual machine and setting up the fingerprint reader within it.

**Comment by udaemon** [comment]
@Dreta can you explain a little bit more in detail what you did? 
because I also can not initialize the reader. and while I can set up my fingerprint in a windows VM I don't know how to use that when in linux. are you using open-fprintd then? I always get this back:

`me@T460s ~ [1]> fprintd-verify me`
`list_devices failed:`

any hint is warmly welcome!
:)

**Comment by Dreta** [comment]
I set up a Windows 10 virtual machine In VirtualBox (remembering to install
the guest additions and Oracle's extension pack for USB support).
Afterwards, I installed the drivers for this fingerprint reader in the virtual machine, found on Lenovo's website. Then I set up the fingerprint
reader using Windows Hello found in the settings.

It did work in Windows, but after trying it in Linux (Arch), it didn't work, always showing an "unknown-error" when trying to enroll a finger. I
ultimately gave up. I was using the fprintd found in Arch's repository.

**Comment by udaemon** [comment]
@Dreta, thanks for replying. which fingerprint reader do you have? 138a:0090 or 138a:0097?
If it's the first one you might check out this: https://github.com/uunicorn/python-validity/issues/129
At least, I'm confident to get it working with some help from there. :)
cheers!

**Comment by Dreta** [comment]
Thank you! I have 138a:0097.

**Comment by udaemon** [comment]
> Thank you! I have 138a:0097.

hi Dreta, just got 138a:0097 in a thinkpad x270 working. if you still have this problem, get back here, maybe I can help you. 
:)

**Comment by Dreta** [comment]
Thank you! I got a new laptop recently, and there are no longer issues with
the fingerprint sensor.

**Comment by mRyan-Patt** [comment]
> > Thank you! I have 138a:0097.
> 
> hi Dreta, just got 138a:0097 in a thinkpad x270 working. if you still have this problem, get back here, maybe I can help you. :)

Do you remember how you did this? I have a thinkpad 470s with that in it and I can't get it to work.

**Comment by udaemon** [comment]
> Do you remember how you did this? I have a thinkpad 470s with that in it and I can't get it to work.

hey, don't remember exactly, how got it running. 
can you describe more in detail what's failing?
