### ISSUE TITLE
Fail to run -t led-dance or enroll command

### ISSUE THREAD

**Issue by xuno2012** [3v1n0/libfprint#48]
my laptop is dual system on WIN11 23H3&archlinux
i am already enroll my finger on WIN11
after `yay -S validity-sensors-tools-git libfprint-vfs009x-git` 
now mine 138a:0090 sensor can be recognition
but run `-t led-dance -t enroll` command output the same error
`➜  ~ sudo validity-sensors-tools -t led-dance
Found device <DEVICE ID 138a:0090 on Bus 001 Address 005>
Opening device 0x90
Traceback (most recent call last):
  File "/usr/bin/validity-sensors-tools", line 375, in <module>
    vfs_tools.open_device(init=True)
  File "/usr/bin/validity-sensors-tools", line 128, in open_device
    vfs_tls.open()
  File "/usr/lib/python3.12/site-packages/proto9x/tls.py", line 126, in open
    self.make_cert_verify()) +
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proto9x/tls.py", line 243, in make_cert_verify
    s=sign(hexlify(buf).decode(), self.priv_key, prehashed=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fastecdsa/ecdsa.py", line 50, in sign
    hex_digest = hexlify(msg).decode()
                 ^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
`
does it means the fingerprint information is already exist on my sensor flash-chip or what?
what should i do?

**Comment by xuno2012** [comment]
if i run initializer or factory-reset command
the program will ruin my fingerprint when i login with WIN11?

**Comment by xuno2012** [comment]
sorry i notice run initialization command same issue https://github.com/3v1n0/libfprint/issues/41 Flash is already partitioned 
i am a newbie

**Comment by xuno2012** [comment]
sorry i notice run initialization command notice the same issue https://github.com/3v1n0/libfprint/issues/41 Flash is already partitioned 
i am a newbie

**Comment by xuno2012** [comment]
sorry i notice run initialization command notice the same issue https://github.com/3v1n0/libfprint/issues/41 Flash is already partitioned 
i am a newbie
